nelmio_cors:
  defaults:
    allow_origin:
      - http://localhost:3000
      - http://127.0.0.1:5500
      - https://eco-ride-front.vercel.app
      - https://eco-ride-front-git-main-aurelies-projects-dcbacd1a.vercel.app
    allow_headers: ["Content-Type", "Authorization", "X-AUTH-TOKEN"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    max_age: 3600
    allow_credentials: true

  paths:
    "^/api/":
      allow_origin:
        - http://localhost:3000
        - http://127.0.0.1:5500
        - https://eco-ride-front.vercel.app
        - https://eco-ride-front-git-main-aurelies-projects-dcbacd1a.vercel.app
      allow_headers: ["Content-Type", "Authorization", "X-AUTH-TOKEN"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allow_credentials: true
      max_age: 3600
