nelmio_cors:
  defaults:
    allow_origin: []
    allow_headers: ["Content-Type", "Authorization", "X-AUTH-TOKEN"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    max_age: 3600
    allow_credentials: true

  paths:
    "^/api/":
      allow_origin:
        - ["http://localhost:3000"]
        - "https://ecoridefront.netlify.app" #   Ajoute ton domaine ici
      allow_headers: ["Content-Type", "Authorization", "X-AUTH-TOKEN"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allow_credentials: true
      max_age: 3600
